const express = require('express')
const router = express.Router()
const PaymentController = require('../controllers/paymentController')

router.get('/getPaymentById/:id',PaymentController.getPaymentById)
router.get('/getPaymentByUserId/:id',PaymentController.getPaymentByUserId)
router.get('/getPayment',PaymentController.getPayment)
router.post('/createrZalopay',PaymentController.createrZalopay)
router.post('/callbackZalopay',PaymentController.callbackZalopay)
router.post('/createrVnpay',PaymentController.createrVnpay)
router.get('/vnpay-return/:query',PaymentController.returnVnpay)
router.post('/callback',PaymentController.callback)
router.post('/status',PaymentController.status)
router.post('/',PaymentController.payment)
router.get('/getPaymentByCinemaId/:id',PaymentController.getPaymentByCinemaId)
router.get('/getPaymentByMovie',PaymentController.getPaymentByMovie)
module.exports = router;